<?php
echo addcslashes(index.html, 'A..z.');
echo "<br>";

echo addslashes("guru's");
echo "<br>";
echo bin2hex ( "guru" );
echo "<br>";
echo chop("gurukiran","n");
echo "<br>";
echo chr(97);
echo "<br>";
$str ="this is chunk";
echo chunk_split($str,2);
echo "<br>";
$uucode =  convert_uuencode($str);
echo $uucode;
echo "<br>";
echo "<br>";
echo convert_uudecode ( $uucode );
echo "<br>";
echo count_chars($str,3);
echo "<br>";
echo crc32 ( $str );
echo "<br>";
echo crypt($str, '$2a$07$usesomesillystringforsalt$');
echo "<br>";
$pieces = explode(" ", $str,0);
echo "<br>";
$pieces = explode(" ", $str,2);
echo "<br>";
echo $pieces[0];
echo "<br>";
$hex = hex2bin("6578616d706c65206865782064617461");
echo $hex;
echo "<br>";
$comma_separated = implode(",", $pieces);
echo "$comma_separated";
echo "<br>";
echo lcfirst ( "Guru" );
echo "<br>";
echo ltrim("guru","g");
echo "<br>";
print("print");
echo "<br>";
echo crypt('mypassword');
echo "<br>";
$year = 2018;
$month = 11;
$day = 18;
if (!($fp = fopen('date.txt', 'w'))) {
    return;
}
fprintf($fp, "%04d-%02d-%02d", $year, $month, $day);
echo "<br>";
echo trim("Hello welcome specbee","he");
echo "<br>";
echo levenshtein ( "ello" , "hello",10,10,10 );
echo "<br>";
echo md5($str);
echo "<br>";
echo md5($str,TRUE);
echo "<br>";
echo md5_file("date.txt",TRUE);
echo "<br>";
echo metaphone("hello");
echo "<br>";
echo nl2br("nl2br \n 2nd line");
echo "<br>";
echo number_format(1234,2);
echo "<br>";
echo ord("guru");
echo "<br>";
$strr = "first=value&arr[]=foo+bar&arr[]=baz";
parse_str($strr, $output);
echo $output['first'];
echo $output['arr'][0];
echo $output['arr'][1];
echo "<br>";
echo quoted_printable_encode ( "welcome");
echo "<br>";
echo quotemeta(".\[]$");
echo "<br>";
echo sha1_file("date.txt");
echo "<br>";
$sim = similar_text('worldh', 'helloo', $perc);
echo "similarity: $sim ($perc %)\n";
echo "<br>";echo "<br>";
$sim = similar_text('helloo', 'worldh', $perc);
echo "similarity: $sim ($perc %)\n";
echo "<br>";
echo soundex("kiran") ;
echo "<br>";
echo soundex("keeran") ;
echo "<br>";
$auth = "24\tLewis Carroll";
$n = sscanf($auth, "%d\t%s %s", $id, $first, $last);
echo "author id=$id
    $first $last $n";
echo "<br>";
echo str_replace("gk","guru","i am gk",$num);
echo $num;
echo "<br>";
echo str_pad("hello",9,"o",2);
echo "<br>";
echo str_repeat("-",100);
echo "<br>";
$rot=str_rot13("abc-nop");
echo $rot;
echo "<br>";
echo str_shuffle("phpmyadmin");
echo "<br>";
$split = str_split("abcdefg",2 );
echo $split[0];
echo "<br>";
print_r(str_word_count("this is wo2rld count",2,"2"));
echo "<br>";
print_r(str_word_count("this is wo2rld count",2));
echo "<br>";
echo strcasecmp("hello","hello");
echo "<br>";

echo strchr("guru@specbee","@",true);
echo "<br>";
echo strncasecmp("hey","he",2);
echo "<br>";
echo strcspn("hellyo","o",2,-1);
echo "<br>";
$str="<html><head><title>title</title></head><h1>header</h1></html>";
echo strip_tags($str,'<h1>');
echo "<br>";
echo stripcslashes("Hello \World!");
echo "<br>";
echo stripos("hello",l);
echo "<br>";
$str = "hello \\wor\ld";
echo stripslashes($str);
echo "<br>";
$text = 'This is a Simple text.';
echo strpbrk($text, 'mi');
echo "<br>";
echo strncasecmp("hello", "he" , 2);
echo "<br>";
echo strstr("guru kiran",' ');

echo "<br>";
echo strstr("guru kiran",' ',true);
?>